version: 2
updates:
  - package-ecosystem: gradle
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    groups:
      spring:
        patterns:
          - "org.springframework*"
          - "io.spring.*"
      jjwt:
        patterns:
          - "io.jsonwebtoken:*"
      lombok:
        patterns:
          - "org.projectlombok:*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-eslint/*"
          - "ngxtension"
      eslint:
        patterns:
          - "eslint*"
          - "*-eslint*"
          - "typescript-eslint"
      transloco:
        patterns:
          - "@jsverse/*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
